#include <SFML/Graphics.hpp>
#include <cmath>
#include <iostream>
#include <algorithm>

const int H = 50;  //50
const int W = 350; //240

String firstLevelMap[H] = {

    " 00                                                                                                                                                                                                                                             ",
    "                                                                                                                                                                                                                                                ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B  BBBBB                                      BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB      BBBBB                                                                                                                                                 ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                           1              H            1                                       ",
    "B                                                                                                                                                                           BBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                       ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                                                               ",
    "B              1               H     1                                                                                                                                BBBB                                                                      ",
    "B              BBBBBBBBBBBBBBBBBBBBBBB                                                                                                                                                                                                          ",
    "B                                                                                                                                                               BBB                                                                            ",
    "B                                                                                                                                                                                                                                              ",
    "B          BBB                                                                                                                                                                                                                                 ",
    "B                                                                                                                                                        BBB                                                                                   ",
    "B                                                                                                                         1          H               1                                                                  1               2  1    ",
    "B       BBB                                                                                                               BBBBBBBBBBBBBBBBBBBBBBBBBBBB                                                                  BBBBBBBBBBBBBBBBBBBB    ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                   BBB                                                                               BB                                        ",
    "B                                                                                                                                                                                                               BBB                             ",
    "B BBB                                                                                                                                                                                   1       1                                               ",
    "B                                                                                                                                                                                       BBBBBBBBB                                              ",
    "B                                                                                                             BBB                                                                                                                               ",
    "B 1                                                      1                                                                                                                                                                                       ",
    "B BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                                                                                                                             BBB                                      ",
    "B                                                       B                                             BBBBB                                                                                                                                     ",
    "B                                                       B                                                                                                                                                                                       ",
    "B                                                       B                             1           1                                                                                                           B   1                     1      ",
    "B                                                       BBBBBBBBBBBBB   BBBBBB        BBBBBBBBBBBBB                                                                                                                BBBBBBBBBBBBBBBBBBBBBBB      ",
    "B                                                                    PPP      PPPPPPPP                                                                                                                                                          ",
    "B                                                                                                                                                                                                                                               ",
    "B                                                                                                                                                                                                        BBB                                    ",
    "B                                                                                                                                                                                    1              1                                           ",
    "                                                                                                                                            1          1    B       B      B         BBBBBBBBBBBBBBBB                                           ",
    "                                                                                                                                            BBBBBBBBBBBB                                                                                        ",
    "                                                                                                                                                        PPPPPPPPPPPPPPPPPPPPPPPPPPPP                  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP          ",
    "                                                                                                            1                 H          1                                                                                                      ",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
};

String *firstLevelPtr = firstLevelMap;
